FROM python:3.9.20-slim

WORKDIR /app

COPY requirements.dev.txt .

RUN pip install --no-cache-dir -r requirements.dev.txt

COPY ./src ./src

WORKDIR /app/src

RUN python3 download_model.py

EXPOSE 8000

ENV ENVIRONMENT=dev
ENV OPENSEARCH_ID=admin
ENV OPENSEARCH_PW=Wlsdyd0101

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
