FROM python:3.9.20-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src

WORKDIR /app/src

RUN python3 download_model.py

EXPOSE 8000

ENV ENVIRONMENT=prod
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV CUDA_VISIBLE_DEVICES=0
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
